name: CI Build Setup
description: Sets up build dependencies

inputs:
  xcb:
    description: Install xcb dependencies
    default: 'true'
  wayland:
    description: Install wayland dependencies
    default: 'true'

runs:
  using: composite
  steps:
    - id: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - id: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          discount \
          doxygen \
          fluxbox \
          gdb \
          graphviz \
          jq \
          lcov \
          libpango1.0-dev \
          libxkbcommon-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          libgdk-pixbuf-2.0-dev \
          ninja-build \
          pandoc \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          texi2html \
          texinfo \
          xdotool \
          xfonts-base \
          xterm \
          xutils-dev
      shell: bash
    - id: doxy
      run: git clone https://github.com/davatorium/doxy-coverage
      shell: bash
    - id: apt-wayland
      if: ${{ inputs.wayland  == 'true' }}
      run: |
        sudo apt-get install -y \
          libwayland-dev \
          wayland-protocols
      shell: bash
    - id: apt-xcb
      if: ${{ inputs.xcb  == 'true' }}
      run: |
        sudo apt-get install -y \
          libstartup-notification0-dev \
          libxcb-ewmh-dev \
          libxcb-icccm4-dev \
          libxcb-randr0-dev \
          libxcb-util0-dev \
          libxcb-xinerama0-dev \
          libxcb-xkb-dev \
          libxcb-xrm-dev \
          libxcb-cursor-dev \
          libxcb-imdkit-dev
      shell: bash
    - id: check
      run: |
        curl -L https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz | tar xzf -
        cd check-0.15.2
        ./configure
        make
        sudo make install
        sudo ldconfig
      shell: bash
