name: Doxygen Check
description: Checks for Doxygen warnings

inputs:
  logfile:
    description: Path to doxygen logfile
    required: true

runs:
  using: composite
  steps:
    - id: check
      run: |
        if [[ "$(grep -c warning ${{ inputs.logfile }})" != 0 ]]; then
          echo
          echo Doxygen warnings found:
          grep warning ${{ inputs.logfile }}
          echo

          exit 1
        fi

        python2 ./doxy-coverage/doxy-coverage.py builddir/doc/html/xml/
      shell: bash
