name: Bug Report
description: Report a problem in Rofi
labels: [bug]
title: "[BUG] "
body:

  - type: markdown
    attributes:
      value: |
        First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! This is not optional for any report. People must be able to understand the full context of the report when reading it, at any time.

        If you feel like you “it is simple and requires no explanation”, please
        consider you’re wrong and still fill the full report. Any report
        missing required informations will be labeled as “Incomplete Report -
        Please follow the guidelines” and will be closed. If you ask a
        question, enter dummy information in required fields to get past the
        checks or in general completely ignore the guidelines, the issue will
        be closed and locked as spam.

        If you are unsure, please use the
        [discussion](https://github.com/davatorium/rofi/discussions) forum
        first. It is easy to upgrade a question to an issue in github.

        If you report problems with speed in rofi, attach a [timing
        trace](https://github.com/davatorium/rofi/blob/next/doc/rofi-debugging.5.markdown#timing-traces).

        **Please do not submit reports related to wayland, see
        [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more
        information.**

  - type: input
    attributes:
      label: "Rofi version (rofi -v)"
      placeholder: "Version: 1.7.5"
    validations:
      required: true
  - type: input
    attributes:
      label: "Configuration"
      description: |
        Please use https://gist.github.com and include output of `rofi -dump-config`.
        n/a is not a valid config.
      placeholder: "Gist URL"
    validations:
      required: true
  - type: input
    attributes:
      label: "Theme"
      description: |
        Please use https://gist.github.com and include output of `rofi -dump-theme`.
        n/a is not a valid theme.
      placeholder: "Gist URL"
    validations:
      required: true
  - type: input
    attributes:
      label: "Timing report"
      description: |
        Please use https://gist.github.com and include output of your command with G_MESSAGES_DEBUG=Timings set.
      placeholder: "Gist URL"
    validations:
      required: false
  - type: input
    attributes:
      label: "Launch command"
      placeholder: "rofi -show drun"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Step to reproduce"
      placeholder: |
        * Step 1
        * Step 2
        * ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe the behavior you expect. May include logs, images, or videos."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behavior"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional information"
    validations:
      required: false
  - type: checkboxes
    id: wayland
    attributes:
      label: Using wayland display server protocol
      description: I have checked and confirm that I am not using wayland as display server protocol. See [here](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more        information.
      options:
        - label: "No, I don't use the wayland display server protocol"
          required: true
  - type: checkboxes
    id: latestversion
    attributes:
      label: I've checked if the issue exists in the latest stable release
      description: I confirm that I verified the issue still exists in the latest stable release. 
      options:
        - label: "Yes, I have checked the problem exists in the latest stable version"
          required: false
      


