.nh
.TH ROFI-KEYS 5 rofi-keys
.SH NAME
.PP
\fBrofi keys\fP - Rofi Key and Mouse bindings

.SH DESCRIPTION
.PP
\fBrofi\fP supports overriding of any of it key and mouse binding.

.SH Setting binding
.PP
Bindings can be done on the commandline (-{bindingname}):

.PP
.RS

.nf
rofi -show run -kb-accept-entry 'Control+Shift+space'

.fi
.RE

.PP
or via the configuration file:

.PP
.RS

.nf
configuration {
  kb-accept-entry: "Control+Shift+space";
}

.fi
.RE

.PP
The key can be set by its name (see above) or its keycode:

.PP
.RS

.nf
configuration {
  kb-accept-entry: "Control+Shift+[65]";
}

.fi
.RE

.PP
An easy way to look up keycode is xev(1).

.PP
Multiple keys can be specified for an action as a comma separated list:

.PP
.RS

.nf
configuration {
  kb-accept-entry: "Control+Shift+space,Return";
}

.fi
.RE

.PP
By Default \fBrofi\fP reacts on pressing, to act on the release of all keys
prepend the binding with \fB\fC!\fR:

.PP
.RS

.nf
configuration {
  kb-accept-entry: "!Control+Shift+space,Return";
}

.fi
.RE

.SH Keyboard Bindings
.SS \fBkb-primary-paste\fP:
.PP
Paste primary selection

.PP
\fBDefault\fP: 	Control+V,Shift+Insert

.SS \fBkb-secondary-paste\fP
.PP
Paste clipboard

.PP
\fBDefault\fP: 	Control+v,Insert

.SS \fBkb-clear-line\fP
.PP
Clear input line

.PP
\fBDefault\fP: 	Control+w

.SS \fBkb-move-front\fP
.PP
Beginning of line

.PP
\fBDefault\fP: 	Control+a

.SS \fBkb-move-end\fP
.PP
End of line

.PP
\fBDefault\fP: 	Control+e

.SS \fBkb-move-word-back\fP
.PP
Move back one word

.PP
\fBDefault\fP: 	Alt+b,Control+Left

.SS \fBkb-move-word-forward\fP
.PP
Move forward one word

.PP
\fBDefault\fP: 	Alt+f,Control+Right

.SS \fBkb-move-char-back\fP
.PP
Move back one char

.PP
\fBDefault\fP: 	Left,Control+b

.SS \fBkb-move-char-forward\fP
.PP
Move forward one char

.PP
\fBDefault\fP: 	Right,Control+f

.SS \fBkb-remove-word-back\fP
.PP
Delete previous word

.PP
\fBDefault\fP: 	Control+Alt+h,Control+BackSpace

.SS \fBkb-remove-word-forward\fP
.PP
Delete next word

.PP
\fBDefault\fP: 	Control+Alt+d

.SS \fBkb-remove-char-forward\fP
.PP
Delete next char

.PP
\fBDefault\fP: 	Delete,Control+d

.SS \fBkb-remove-char-back\fP
.PP
Delete previous char

.PP
\fBDefault\fP: 	BackSpace,Shift+BackSpace,Control+h

.SS \fBkb-remove-to-eol\fP
.PP
Delete till the end of line

.PP
\fBDefault\fP: 	Control+k

.SS \fBkb-remove-to-sol\fP
.PP
Delete till the start of line

.PP
\fBDefault\fP: 	Control+u

.SS \fBkb-accept-entry\fP
.PP
Accept entry

.PP
\fBDefault\fP: 	Control+j,Control+m,Return,KP_Enter

.SS \fBkb-accept-custom\fP
.PP
Use entered text as command (in ssh/run modes)

.PP
\fBDefault\fP: 	Control+Return

.SS \fBkb-accept-custom-alt\fP
.PP
Use entered text as command (in ssh/run modes)

.PP
\fBDefault\fP: 	Control+Shift+Return

.SS \fBkb-accept-alt\fP
.PP
Use alternate accept command.

.PP
\fBDefault\fP: 	Shift+Return

.SS \fBkb-delete-entry\fP
.PP
Delete entry from history

.PP
\fBDefault\fP: 	Shift+Delete

.SS \fBkb-mode-next\fP
.PP
Switch to the next mode.

.PP
\fBDefault\fP: 	Shift+Right,Control+Tab

.SS \fBkb-mode-previous\fP
.PP
Switch to the previous mode.

.PP
\fBDefault\fP: 	Shift+Left,Control+ISO_Left_Tab

.SS \fBkb-mode-complete\fP
.PP
Start completion for mode.

.PP
\fBDefault\fP: 	Control+l

.SS \fBkb-row-left\fP
.PP
Go to the previous column

.PP
\fBDefault\fP: 	Control+Page_Up

.SS \fBkb-row-right\fP
.PP
Go to the next column

.PP
\fBDefault\fP: 	Control+Page_Down

.SS \fBkb-row-up\fP
.PP
Select previous entry

.PP
\fBDefault\fP: 	Up,Control+p

.SS \fBkb-row-down\fP
.PP
Select next entry

.PP
\fBDefault\fP: 	Down,Control+n

.SS \fBkb-row-tab\fP
.PP
Go to next row, if one left, accept it, if no left next mode.

.PP
\fBDefault\fP: 	

.SS \fBkb-element-next\fP
.PP
Go to next row.

.PP
\fBDefault\fP: Tab	

.SS \fBkb-element-prev\fP
.PP
Go to previous row.

.PP
\fBDefault\fP: ISO_Left_Tab

.SS \fBkb-page-prev\fP
.PP
Go to the previous page

.PP
\fBDefault\fP: 	Page_Up

.SS \fBkb-page-next\fP
.PP
Go to the next page

.PP
\fBDefault\fP: 	Page_Down

.SS \fBkb-row-first\fP
.PP
Go to the first entry

.PP
\fBDefault\fP: 	Home,KP_Home

.SS \fBkb-row-last\fP
.PP
Go to the last entry

.PP
\fBDefault\fP: 	End,KP_End

.SS \fBkb-row-select\fP
.PP
Set selected item as input text

.PP
\fBDefault\fP: 	Control+space

.SS \fBkb-screenshot\fP
.PP
Take a screenshot of the rofi window

.PP
\fBDefault\fP: 	Alt+S

.SS \fBkb-ellipsize\fP
.PP
Toggle between ellipsize modes for displayed data

.PP
\fBDefault\fP: 	Alt+period

.SS \fBkb-toggle-case-sensitivity\fP
.PP
Toggle case sensitivity

.PP
\fBDefault\fP: 	grave,dead_grave

.SS \fBkb-toggle-sort\fP
.PP
Toggle sort

.PP
\fBDefault\fP: 	Alt+grave

.SS \fBkb-cancel\fP
.PP
Quit rofi

.PP
\fBDefault\fP: 	Escape,Control+g,Control+bracketleft

.SS \fBkb-custom-1\fP
.PP
Custom keybinding 1

.PP
\fBDefault\fP: 	Alt+1

.SS \fBkb-custom-2\fP
.PP
Custom keybinding 2

.PP
\fBDefault\fP: 	Alt+2

.SS \fBkb-custom-3\fP
.PP
Custom keybinding 3

.PP
\fBDefault\fP: 	Alt+3

.SS \fBkb-custom-4\fP
.PP
Custom keybinding 4

.PP
\fBDefault\fP: 	Alt+4

.SS \fBkb-custom-5\fP
.PP
Custom Keybinding 5

.PP
\fBDefault\fP: 	Alt+5

.SS \fBkb-custom-6\fP
.PP
Custom keybinding 6

.PP
\fBDefault\fP: 	Alt+6

.SS \fBkb-custom-7\fP
.PP
Custom Keybinding 7

.PP
\fBDefault\fP: 	Alt+7

.SS \fBkb-custom-8\fP
.PP
Custom keybinding 8

.PP
\fBDefault\fP: 	Alt+8

.SS \fBkb-custom-9\fP
.PP
Custom keybinding 9

.PP
\fBDefault\fP: 	Alt+9

.SS \fBkb-custom-10\fP
.PP
Custom keybinding 10

.PP
\fBDefault\fP: 	Alt+0

.SS \fBkb-custom-11\fP
.PP
Custom keybinding 11

.PP
\fBDefault\fP: 	Alt+exclam

.SS \fBkb-custom-12\fP
.PP
Custom keybinding 12

.PP
\fBDefault\fP: 	Alt+at

.SS \fBkb-custom-13\fP
.PP
Custom keybinding 13

.PP
\fBDefault\fP: 	Alt+numbersign

.SS \fBkb-custom-14\fP
.PP
Custom keybinding 14

.PP
\fBDefault\fP: 	Alt+dollar

.SS \fBkb-custom-15\fP
.PP
Custom keybinding 15

.PP
\fBDefault\fP: 	Alt+percent

.SS \fBkb-custom-16\fP
.PP
Custom keybinding 16

.PP
\fBDefault\fP: 	Alt+dead_circumflex

.SS \fBkb-custom-17\fP
.PP
Custom keybinding 17

.PP
\fBDefault\fP: 	Alt+ampersand

.SS \fBkb-custom-18\fP
.PP
Custom keybinding 18

.PP
\fBDefault\fP: 	Alt+asterisk

.SS \fBkb-custom-19\fP
.PP
Custom Keybinding 19

.PP
\fBDefault\fP: 	Alt+parenleft

.SS \fBkb-select-1\fP
.PP
Select row 1

.PP
\fBDefault\fP: 	Super+1

.SS \fBkb-select-2\fP
.PP
Select row 2

.PP
\fBDefault\fP: 	Super+2

.SS \fBkb-select-3\fP
.PP
Select row 3

.PP
\fBDefault\fP: 	Super+3

.SS \fBkb-select-4\fP
.PP
Select row 4

.PP
\fBDefault\fP: 	Super+4

.SS \fBkb-select-5\fP
.PP
Select row 5

.PP
\fBDefault\fP: 	Super+5

.SS \fBkb-select-6\fP
.PP
Select row 6

.PP
\fBDefault\fP: 	Super+6

.SS \fBkb-select-7\fP
.PP
Select row 7

.PP
\fBDefault\fP: 	Super+7

.SS \fBkb-select-8\fP
.PP
Select row 8

.PP
\fBDefault\fP: 	Super+8

.SS \fBkb-select-9\fP
.PP
Select row 9

.PP
\fBDefault\fP: 	Super+9

.SS \fBkb-select-10\fP
.PP
Select row 10

.PP
\fBDefault\fP: 	Super+0

.SH Mouse Bindings
.SS \fBml-row-left\fP
.PP
Go to the previous column

.PP
\fBDefault\fP: 	ScrollLeft

.SS \fBml-row-right\fP
.PP
Go to the next column

.PP
\fBDefault\fP: 	ScrollRight

.SS \fBml-row-up\fP
.PP
Select previous entry

.PP
\fBDefault\fP: 	ScrollUp

.SS \fBml-row-down\fP
.PP
Select next entry

.PP
\fBDefault\fP: 	ScrollDown

.SS \fBme-select-entry\fP
.PP
Select hovered row

.PP
\fBDefault\fP: 	MousePrimary

.SS \fBme-accept-entry\fP
.PP
Accept hovered row

.PP
\fBDefault\fP: 	MouseDPrimary

.SS \fBme-accept-custom\fP
.PP
Accept hovered row with custom action

.PP
\fBDefault\fP: 	Control+MouseDPrimary

.SH SEE ALSO
.PP
rofi(1), rofi-sensible-terminal(1), rofi-theme(5), rofi-script(5)

.SH AUTHOR
.PP
Qball Cow qball@gmpclient.org
\[la]mailto:qball@gmpclient.org\[ra]

.PP
Rasmus Steinke rasi@xssn.at
\[la]mailto:rasi@xssn.at\[ra]

.PP
Morgane Glidic sardemff7+rofi@sardemff7.net
\[la]mailto:sardemff7+rofi@sardemff7.net\[ra]

.PP
Original code based on work by: Sean Pringle sean.pringle@gmail.com
\[la]mailto:sean.pringle@gmail.com\[ra]

.PP
For a full list of authors, check the AUTHORS file.
