.nh
.TH rofi-theme-selector 1 rofi-theme-selector
.SH NAME
.PP
\fBrofi-theme-selector\fP - Preview and apply themes for \fBrofi\fP

.SH DESCRIPTION
.PP
\fBrofi-theme-selector\fP is a bash/rofi script to preview and apply themes for \fBrofi\fP\&.
It's part of any installation of \fBrofi\fP\&.

.SH USAGE
.SS Running rofi-theme-selector
.PP
\fBrofi-theme-selector\fP shows a list of all available themes in a \fBrofi\fP window.
It lets you preview each theme with the Enter key and apply the theme to your
\fBrofi\fP configuration file with Alt+a.

.SH Theme directories
.PP
\fBrofi-theme-selector\fP searches the following directories for themes:

.RS
.IP \(bu 2
${PREFIX}/share/rofi/themes
.IP \(bu 2
$XDG_CONFIG_HOME/rofi/themes
.IP \(bu 2
$XDG_DATA_HOME/share/rofi/themes

.RE

.PP
${PREFIX} reflects the install location of rofi. In most cases this will be "/usr".
$XDG_CONFIG_HOME is normally unset. Default path is "$HOME/.config".
$XDG_DATA_HOME is normally unset. Default path is "$HOME/.local/share".

.SH SEE ALSO
.PP
rofi(1)

.SH AUTHORS
.PP
Qball Cow qball@gmpclient.org
Rasmus Steinke rasi@xssn.at
