.nh
.TH rofi-sensible-terminal 1 rofi-sensible-terminal
.SH NAME
.PP
\fBrofi-sensible-terminal\fP -  launches $TERMINAL with fallbacks

.SH SYNOPSIS
.PP
rofi-sensible-terminal [arguments]

.SH DESCRIPTION
.PP
rofi-sensible-terminal is invoked in the rofi default config to start a terminal. This
wrapper script is necessary since there is no distribution-independent terminal launcher
(but for example Debian has x-terminal-emulator). Distribution packagers are responsible for
shipping this script in a way which is appropriate for the distribution.

.PP
It tries to start one of the following (in that order):

.RS
.IP \(bu 2
\fB\fC$TERMINAL\fR (this is a non-standard variable)
.IP \(bu 2
x-terminal-emulator
.IP \(bu 2
urxvt
.IP \(bu 2
rxvt
.IP \(bu 2
st
.IP \(bu 2
terminology
.IP \(bu 2
qterminal
.IP \(bu 2
Eterm
.IP \(bu 2
aterm
.IP \(bu 2
uxterm
.IP \(bu 2
xterm
.IP \(bu 2
roxterm
.IP \(bu 2
xfce4-terminal.wrapper
.IP \(bu 2
mate-terminal
.IP \(bu 2
lxterminal
.IP \(bu 2
konsole
.IP \(bu 2
alacritty
.IP \(bu 2
kitty

.RE

.SH SEE ALSO
.PP
rofi(1)

.SH AUTHORS
.PP
Dave Davenport and contributors

.PP
Copied script from i3:
Michael Stapelberg and contributors
