! ------------------------------------------------------------------------------
! ROFI Color theme
! User: Rasi
! Copyright: Rasmus Steinke
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #0039ff, #0039ff, #4F80FF
rofi.color-normal: #0039ff, #4f80ff, #0039ff, #4f80ff, #ffffff
rofi.color-active: #0039ff, #68ba50, #0039ff, #4f80ff, #68ba50
rofi.color-urgent: #0039ff, #ff7047, #0039ff, #4f80ff, #ff7047
