#ifndef ROFI_DEFAULT_THEME
#define ROFI_DEFAULT_THEME 

const char *default_theme =
"* {"
"    spacing:    2;"
"    background: #00000000;"
"}"
"#window {"
"    border:     1;"
"    foreground: #FF002B36;"
"    padding:    5;"
"    background: #FFFDF6E3;"
"}"
"#window.mainbox {"
"    border:  0;"
"    padding: 0;"
"}"
"#window.mainbox.message.box {"
"    border:  1px dash 0px 0px ;"
"    padding: 2px 0px 0px ;"
"}"
"#window.mainbox.message.normal {"
"    foreground: #FF002B36;"
"    background: #FFFDF6E3;"
"}"
"#window.mainbox.listview {"
"    fixed-height: 0;"
"    border:       1px dash 0px 0px ;"
"    columns:      1;"
"    padding:      2px 0px 0px ;"
"}"
"#window.mainbox.listview.element {"
"    border: 0;"
"}"
"#window.mainbox.listview.element.normal.normal {"
"    foreground: #FF002B36;"
"    background: #FFFDF6E3;"
"}"
"#window.mainbox.listview.element.normal.urgent {"
"    foreground: #FFDC322F;"
"    background: #FFFDF6E3;"
"}"
"#window.mainbox.listview.element.normal.active {"
"    foreground: #FF268BD2;"
"    background: #FFFDF6E3;"
"}"
"#window.mainbox.listview.element.selected.normal {"
"    foreground: #FFEEE8D5;"
"    background: #FF586E75;"
"}"
"#window.mainbox.listview.element.selected.urgent {"
"    foreground: #FFFDF6E3;"
"    background: #FFDC322F;"
"}"
"#window.mainbox.listview.element.selected.active {"
"    foreground: #FFFDF6E3;"
"    background: #FF268BD2;"
"}"
"#window.mainbox.listview.element.alternate.normal {"
"    foreground: #FF002B36;"
"    background: #FFEEE8D5;"
"}"
"#window.mainbox.listview.element.alternate.urgent {"
"    foreground: #FFDC322F;"
"    background: #FFEEE8D5;"
"}"
"#window.mainbox.listview.element.alternate.active {"
"    foreground: #FF268BD2;"
"    background: #FFEEE8D5;"
"}"
"#window.mainbox.listview.scrollbar {"
"    border:  0;"
"    padding: 0;"
"}"
"#window.mainbox.sidebar.box {"
"    border: 1px dash 0px 0px ;"
"}"
"#window.mainbox.inputbar {"
"    spacing: 0;"
"}"
"#window.mainbox.inputbar.box {"
"}"
"#window.mainbox.inputbar.normal {"
"    foreground: #FF002B36;"
"    background: #FFFDF6E3;"
"}";
#endif
