name: Meson Build
description: Builds Rofi using Meson

inputs:
  cc:
    description: Compiler to use
    required: true

runs:
  using: composite
  steps:
    - id: pip
      run: pip install meson ninja
      shell: bash
    - id: setup
      run: meson setup builddir -Db_coverage=true
      shell: bash
      env:
        CC: ${{ inputs.cc }}
    - id: build
      run: ninja -C builddir
      shell: bash
    - id: dist
      run: ninja -C builddir dist
      shell: bash
    - id: test
      run: ninja -C builddir test
      shell: bash
    - id: doxy
      run: ninja -C builddir doc/html > doxygen.log 2>&1 
      shell: bash
    - id: doxycheck
      uses: ./.github/actions/doxycheck
      with:
        logfile: doxygen.log
