name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - sphinx
      - next

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          CONFIG_FILE: mkdocs/mkdocs.yml 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
